base_model: cyberagent/open-calm-small
output_dir: ./open-small-qlora-out

model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer
is_llama_derived_model: false
trust_remote_code: true

load_in_8bit: false
load_in_4bit: true
strict: false

datasets:
  - path: train-5-inst.json
    type:
      system_prompt: ""
      field_system: system
      format: "{instruction}"
      no_input_format: "{instruction}"

dataset_prepared_path:
val_set_size: 0.05

adapter: qlora
lora_model_dir:

sequence_len: 512
sample_packing: false
pad_to_sequence_len:

lora_r: 64
lora_alpha: 16
lora_dropout: 0.05
lora_target_linear: true
lora_fan_in_fan_out:
lora_target_modules:
  - query_key_value

wandb_project:
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 16
micro_batch_size: 4
num_epochs: 3
optimizer: paged_adamw_32bit
lr_scheduler: cosine
learning_rate: 0.00055

train_on_inputs: false
group_by_length: false
bf16: false
fp16: true
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint: false
local_rank:
logging_steps: 1
xformers_attention: false
flash_attention: false

warmup_steps: 10
eval_steps: 0.05
eval_table_size:
save_steps:
debug: false
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
